/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication2;

import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.Date;


/**
 *
 * @author MARK
 */


public class AddEmp extends javax.swing.JFrame {

    /**
     * Creates new form AddEmp
     */
    public AddEmp() {
        initComponents();
        Random random = new Random();
        int employeeNo = random.nextInt(10) * 1000 + random.nextInt(10) * 100 + random.nextInt(10) * 10 + random.nextInt(10);
        System.out.println(employeeNo);
        
        EmpNo.setText(String.valueOf(employeeNo)); //Inassign ko yung random integer sa text
        
       /* int no = Integer.parseInt(EmpNo.getText());
        System.out.print(no); 
        Ito yung code if ever gusto mo kunin yung VALUE na nasa loob ng EmpNo na jLabel
        Importante toh sa index nung SQL data
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        EmpNo = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        Label1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        NonExemptCheckBox = new javax.swing.JCheckBox();
        ExemptCheckBox = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        IntroductoryCheckBox = new javax.swing.JCheckBox();
        RegCheckBox = new javax.swing.JCheckBox();
        PTCheckBox = new javax.swing.JCheckBox();
        TempCheckBox = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        SeparatedRadioButton = new javax.swing.JRadioButton();
        SingleRadioButton = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        MarriedRadioButton = new javax.swing.JRadioButton();
        WidowedRadioButton = new javax.swing.JRadioButton();
        jTextField6 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        QuitWNRadioButton = new javax.swing.JRadioButton();
        QuitWoNRadioButton = new javax.swing.JRadioButton();
        EndOfAssRadioButton = new javax.swing.JRadioButton();
        LaidOffRadioButton = new javax.swing.JRadioButton();
        TerminatedRadioButton = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        YesCheckBox = new javax.swing.JCheckBox();
        NoCheckBox = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 540, 260));

        EmpNo.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        EmpNo.setText("0000");
        jPanel1.add(EmpNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, 30));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 279, 30));

        jLabel2.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel2.setText("Employee Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel3.setText("Position");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 279, 30));

        jLabel4.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel4.setText("Department");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 279, 30));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 90, 30));

        jLabel5.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel5.setText("Per");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, -1, -1));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 90, 30));

        Label1.setFont(new java.awt.Font("Poppins ExtraBold", 1, 14)); // NOI18N
        Label1.setText("Termination of Employment (Leave blank if not applicable)");
        jPanel1.add(Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 820, -1, 30));

        jLabel8.setText(".");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 970, 110, -1));

        jLabel9.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel9.setText("Pay Rate");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        NonExemptCheckBox.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        NonExemptCheckBox.setText("Non-Exempt");
        NonExemptCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NonExemptCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(NonExemptCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, 20));

        ExemptCheckBox.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        ExemptCheckBox.setText("Exempt");
        ExemptCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExemptCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(ExemptCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, 20));

        jLabel10.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel10.setText("Tax Exemption");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));

        jLabel11.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel11.setText("Marital Status");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, 20));

        IntroductoryCheckBox.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        IntroductoryCheckBox.setText("Introductory");
        IntroductoryCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntroductoryCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(IntroductoryCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, 20));

        RegCheckBox.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        RegCheckBox.setText("Regular Full Time");
        RegCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(RegCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, -1, 20));

        PTCheckBox.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        PTCheckBox.setText("Part-Time");
        PTCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PTCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(PTCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, -1, 20));

        TempCheckBox.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        TempCheckBox.setText("Temporary");
        TempCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TempCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(TempCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, -1, 20));

        jLabel12.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel12.setText("Eligible For Rehire?");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 890, -1, 20));

        SeparatedRadioButton.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        SeparatedRadioButton.setText("Seperated");
        SeparatedRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeparatedRadioButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SeparatedRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, -1, -1));

        SingleRadioButton.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        SingleRadioButton.setText("Single");
        SingleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SingleRadioButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SingleRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, -1, -1));

        jButton1.setBackground(new java.awt.Color(102, 0, 102));
        jButton1.setFont(new java.awt.Font("Poppins ExtraBold", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 120, 40));

        MarriedRadioButton.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        MarriedRadioButton.setText("Married");
        MarriedRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarriedRadioButtonActionPerformed(evt);
            }
        });
        jPanel1.add(MarriedRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, -1, -1));

        WidowedRadioButton.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        WidowedRadioButton.setText("Widowed");
        WidowedRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WidowedRadioButtonActionPerformed(evt);
            }
        });
        jPanel1.add(WidowedRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, -1, -1));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 150, 30));

        jLabel13.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel13.setText("Contact Number");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, 30));

        Label2.setFont(new java.awt.Font("Poppins ExtraBold", 0, 24)); // NOI18N
        Label2.setText("Add Employee");
        jPanel1.add(Label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel14.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel14.setText("Classification");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, -1));

        QuitWNRadioButton.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        QuitWNRadioButton.setText("Quit With Notice");
        QuitWNRadioButton.setBorder(null);
        QuitWNRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitWNRadioButtonActionPerformed(evt);
            }
        });
        jPanel1.add(QuitWNRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 860, -1, -1));

        QuitWoNRadioButton.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        QuitWoNRadioButton.setText("Quit Without Notice");
        QuitWoNRadioButton.setBorder(null);
        QuitWoNRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitWoNRadioButtonActionPerformed(evt);
            }
        });
        jPanel1.add(QuitWoNRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 860, -1, -1));

        EndOfAssRadioButton.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        EndOfAssRadioButton.setText("End of Assignment");
        EndOfAssRadioButton.setBorder(null);
        EndOfAssRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndOfAssRadioButtonActionPerformed(evt);
            }
        });
        jPanel1.add(EndOfAssRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 860, -1, 20));

        LaidOffRadioButton.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        LaidOffRadioButton.setText("Laid Off");
        LaidOffRadioButton.setBorder(null);
        LaidOffRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaidOffRadioButtonActionPerformed(evt);
            }
        });
        jPanel1.add(LaidOffRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 860, -1, -1));

        TerminatedRadioButton.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        TerminatedRadioButton.setText("Terminated");
        TerminatedRadioButton.setBorder(null);
        TerminatedRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TerminatedRadioButtonActionPerformed(evt);
            }
        });
        jPanel1.add(TerminatedRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 860, -1, -1));

        jLabel15.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel15.setText("Last Date Worked");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 890, -1, 30));

        YesCheckBox.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        YesCheckBox.setText("Yes");
        YesCheckBox.setBorder(null);
        YesCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(YesCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 890, -1, 20));

        NoCheckBox.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        NoCheckBox.setText("No");
        NoCheckBox.setBorder(null);
        NoCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(NoCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 890, -1, 20));

        jButton2.setBackground(new java.awt.Color(102, 0, 102));
        jButton2.setFont(new java.awt.Font("Poppins ExtraBold", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Add Dependents");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 180, 40));

        jLabel6.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabel6.setText("Employee Number:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 30));

        jButton3.setBackground(new java.awt.Color(102, 0, 102));
        jButton3.setFont(new java.awt.Font("Poppins ExtraBold", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 120, 40));

        jLabel16.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel16.setText("Bonus");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, -1, 30));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 200, 30));

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 900, 140, -1));

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NonExemptCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NonExemptCheckBoxActionPerformed
        // TODO add your handling code here:
        if(NonExemptCheckBox.isSelected()){
            ExemptCheckBox.setSelected(false);
        }
    }//GEN-LAST:event_NonExemptCheckBoxActionPerformed

    private void ExemptCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExemptCheckBoxActionPerformed
        // TODO add your handling code here:
        if(ExemptCheckBox.isSelected()){
            NonExemptCheckBox.setSelected(false);
        }   
    }//GEN-LAST:event_ExemptCheckBoxActionPerformed

    private void IntroductoryCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntroductoryCheckBoxActionPerformed
        // TODO add your handling code here:
        if(IntroductoryCheckBox.isSelected()){
               PTCheckBox.setSelected(false);
               RegCheckBox.setSelected(false);
               TempCheckBox.setSelected(false);
          }
    }//GEN-LAST:event_IntroductoryCheckBoxActionPerformed

    private void RegCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegCheckBoxActionPerformed
        // TODO add your handling code here:
        if(RegCheckBox.isSelected()){
               PTCheckBox.setSelected(false);
               IntroductoryCheckBox.setSelected(false);
               TempCheckBox.setSelected(false);
          }
    }//GEN-LAST:event_RegCheckBoxActionPerformed

    private void PTCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PTCheckBoxActionPerformed
        // TODO add your handling code here:
        if(PTCheckBox.isSelected()){
                RegCheckBox.setSelected(false);
                IntroductoryCheckBox.setSelected(false);
                TempCheckBox.setSelected(false);
           }
    }//GEN-LAST:event_PTCheckBoxActionPerformed

    private void TempCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TempCheckBoxActionPerformed
        // TODO add your handling code here:
        if(TempCheckBox.isSelected()){
              RegCheckBox.setSelected(false);
              IntroductoryCheckBox.setSelected(false);
              PTCheckBox.setSelected(false);
          } 
    }//GEN-LAST:event_TempCheckBoxActionPerformed

    private void QuitWNRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitWNRadioButtonActionPerformed
        // TODO add your handling code here:
        if(QuitWNRadioButton.isSelected()){
            QuitWoNRadioButton.setSelected(false);
            TerminatedRadioButton.setSelected(false);
            LaidOffRadioButton.setSelected(false);
            EndOfAssRadioButton.setSelected(false);
        }
    }//GEN-LAST:event_QuitWNRadioButtonActionPerformed

    private void EndOfAssRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndOfAssRadioButtonActionPerformed
        // TODO add your handling code here:
        if(EndOfAssRadioButton.isSelected()){
            QuitWoNRadioButton.setSelected(false);
            TerminatedRadioButton.setSelected(false);
            LaidOffRadioButton.setSelected(false);
            QuitWNRadioButton.setSelected(false);
        }        
    }//GEN-LAST:event_EndOfAssRadioButtonActionPerformed

    private void TerminatedRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TerminatedRadioButtonActionPerformed
        // TODO add your handling code here:
        if(TerminatedRadioButton.isSelected()){
            QuitWoNRadioButton.setSelected(false);
            EndOfAssRadioButton.setSelected(false);
            LaidOffRadioButton.setSelected(false);
            QuitWNRadioButton.setSelected(false);
        }          
    }//GEN-LAST:event_TerminatedRadioButtonActionPerformed

    private void QuitWoNRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitWoNRadioButtonActionPerformed
        // TODO add your handling code here:
        if(QuitWoNRadioButton.isSelected()){
            QuitWNRadioButton.setSelected(false);
            EndOfAssRadioButton.setSelected(false);
            LaidOffRadioButton.setSelected(false);
            TerminatedRadioButton.setSelected(false);
        }         
    }//GEN-LAST:event_QuitWoNRadioButtonActionPerformed

    private void YesCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesCheckBoxActionPerformed
        // TODO add your handling code here:
        if(YesCheckBox.isSelected()){
            NoCheckBox.setSelected(false);
        }
    }//GEN-LAST:event_YesCheckBoxActionPerformed

    private void NoCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoCheckBoxActionPerformed
        // TODO add your handling code here:
        if(NoCheckBox.isSelected()){
            YesCheckBox.setSelected(false);
        }
    }//GEN-LAST:event_NoCheckBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            // Retrive Text
            int empno = Integer.parseInt(EmpNo.getText()); 
            String empname=jTextField1.getText();
            String position=jTextField2.getText();
            String department=jTextField3.getText();
            String payrate=jTextField5.getText();
            String per=jTextField4.getText();
            String bonus=jTextField6.getText();
            String contactno=jTextField7.getText();
            String tax;
            String classification;
            String maritalStat;
            String TOE;
            Date LastDateW=jDateChooser1.getDate();
            String Eligibility;
            
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hrdatavault", "root", "mYsT4nd4rdQu3rYL4ngu4g3");
            PreparedStatement ps=con.prepareStatement("INSERT into employee_file(EmpNo,EmpName,Position,Department,PayRate,PR_Per,Bonus,TaxExempt,Classification,MaritalStatus,ContactNo,TOE,LDW,Eligibility)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            ps.setInt(1, empno);
            ps.setString(2, empname);
            ps.setString(3, position);
            ps.setString(4, department);
            ps.setString(5, payrate);
            ps.setString(6, per);
            ps.setString(7, bonus);
             // Tax Exemption Retrieval
            if(ExemptCheckBox.isSelected()){
                tax="Exempt";
                ps.setString(8, tax);
                System.out.println(tax);
            }
            if(NonExemptCheckBox.isSelected()){
                tax="Non-Exempt";
                ps.setString(8, tax);
                System.out.println(tax);
            }
            // Classification Retrieval
            if(IntroductoryCheckBox.isSelected()){
                classification="Introductory";
                ps.setString(9, classification);
                System.out.println(classification);
            }
            if(RegCheckBox.isSelected()){
                classification="Regular";
                ps.setString(9, classification);
                System.out.println(classification);
            }
            if(PTCheckBox.isSelected()){
                classification="Part-Time";
                ps.setString(9, classification);
                System.out.println(classification);
            }
            if(TempCheckBox.isSelected()){
                classification="Temporary";
                ps.setString(9, classification);
                System.out.println(classification);
            }
            // Marital Status Retrieval
            if(SingleRadioButton.isSelected()){
                maritalStat="Single";
                ps.setString(10, maritalStat);
                System.out.println(maritalStat);
            }
            if(MarriedRadioButton.isSelected()){
                maritalStat="Married";
                ps.setString(10, maritalStat);
                System.out.println(maritalStat);
            }
            if(WidowedRadioButton.isSelected()){
                maritalStat="Widowed";
                ps.setString(10, maritalStat);
                System.out.println(maritalStat);
            }
            if(SeparatedRadioButton.isSelected()){
                maritalStat="Separated";
                ps.setString(10, maritalStat);
                System.out.println(maritalStat);
            }
            ps.setString(11, contactno);
            // TOE Retrieval
            if(QuitWNRadioButton.isSelected()){
                TOE="QWN";
                // add if statement because this is optional
                ps.setString(12, TOE);
                System.out.println(TOE);
            }
            else if(QuitWoNRadioButton.isSelected()){
                TOE="QWON";
                ps.setString(12, TOE);
                System.out.println(TOE);
            }
            else if(TerminatedRadioButton.isSelected()){
                TOE="Terminated";
                ps.setString(12, TOE);
                System.out.println(TOE);
            }
            else if(LaidOffRadioButton.isSelected()){
                TOE="Laid Off";
                ps.setString(12, TOE);
                System.out.println(TOE);
            }
            else if(EndOfAssRadioButton.isSelected()){
                TOE="EOA";
                ps.setString(12, TOE);
                System.out.println(TOE);
            }else{
                TOE = null;
                ps.setNull(12, java.sql.Types.VARCHAR);
                System.out.println("TOE is null");
            }
            // Convert java.util.Date to java.sql.Date 
            if (LastDateW != null) { 
                java.sql.Date sqlDate = new java.sql.Date(LastDateW.getTime()); 
                System.out.println("Selected Date (java.sql.Date): " + sqlDate); 
                ps.setDate(13, sqlDate);
            } else { 
                System.out.println("No date selected."); }

            // Eligibility Retrieval
            if(YesCheckBox.isSelected()){
                Eligibility="Yes";
                ps.setString(14, Eligibility);
                System.out.println(Eligibility);
            }
            if(NoCheckBox.isSelected()){
                Eligibility="No";
                ps.setString(14, Eligibility);
                System.out.println(Eligibility);
            }
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Insert Successfully");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddEmp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddEmp.class.getName()).log(Level.SEVERE, null, ex);
        }

 
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void SingleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SingleRadioButtonActionPerformed
        // TODO add your handling code here:
      if(SingleRadioButton.isSelected()){
            MarriedRadioButton.setSelected(false);
            WidowedRadioButton.setSelected(false);
            SeparatedRadioButton.setSelected(false);
        }
    }//GEN-LAST:event_SingleRadioButtonActionPerformed

    private void MarriedRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarriedRadioButtonActionPerformed
        // TODO add your handling code here:
      if(MarriedRadioButton.isSelected()){
            SingleRadioButton.setSelected(false);
            WidowedRadioButton.setSelected(false);
            SeparatedRadioButton.setSelected(false);
        }
    }//GEN-LAST:event_MarriedRadioButtonActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void SeparatedRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeparatedRadioButtonActionPerformed
        // TODO add your handling code here:
      if(SeparatedRadioButton.isSelected()){
            SingleRadioButton.setSelected(false);
            MarriedRadioButton.setSelected(false);
            WidowedRadioButton.setSelected(false);
        }
    }//GEN-LAST:event_SeparatedRadioButtonActionPerformed

    private void WidowedRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WidowedRadioButtonActionPerformed
        // TODO add your handling code here:
      if(WidowedRadioButton.isSelected()){
            SingleRadioButton.setSelected(false);
            MarriedRadioButton.setSelected(false);
            SeparatedRadioButton.setSelected(false);
        }
    }//GEN-LAST:event_WidowedRadioButtonActionPerformed

    private void LaidOffRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaidOffRadioButtonActionPerformed
        // TODO add your handling code here:
        if(LaidOffRadioButton.isSelected()){
            QuitWoNRadioButton.setSelected(false);
            EndOfAssRadioButton.setSelected(false);
            TerminatedRadioButton.setSelected(false);
            QuitWNRadioButton.setSelected(false);
        }      
    }//GEN-LAST:event_LaidOffRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmpNo;
    private javax.swing.JRadioButton EndOfAssRadioButton;
    private javax.swing.JCheckBox ExemptCheckBox;
    private javax.swing.JCheckBox IntroductoryCheckBox;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label2;
    private javax.swing.JRadioButton LaidOffRadioButton;
    private javax.swing.JRadioButton MarriedRadioButton;
    private javax.swing.JCheckBox NoCheckBox;
    private javax.swing.JCheckBox NonExemptCheckBox;
    private javax.swing.JCheckBox PTCheckBox;
    private javax.swing.JRadioButton QuitWNRadioButton;
    private javax.swing.JRadioButton QuitWoNRadioButton;
    private javax.swing.JCheckBox RegCheckBox;
    private javax.swing.JRadioButton SeparatedRadioButton;
    private javax.swing.JRadioButton SingleRadioButton;
    private javax.swing.JCheckBox TempCheckBox;
    private javax.swing.JRadioButton TerminatedRadioButton;
    private javax.swing.JRadioButton WidowedRadioButton;
    private javax.swing.JCheckBox YesCheckBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
