/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package javaapplication2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author MARK
 */
public class EditEmployee extends javax.swing.JInternalFrame {
    private String selectedString;
    /**
     * Creates new form Menu1
     */
    public EditEmployee() {
  
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        display_employee();              
           
    }
    
      public ArrayList<Employee> employeeList(){
        ArrayList<Employee> employeeList = new ArrayList<>();
        
        try {
        Class.forName("com.mysql.cj.jdbc.Driver");        
        Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/hrdatavault", "root", "@forgotpassword123");
        System.out.print("Connected");
        String query1= "SELECT * FROM employee";
        Statement statement = connection.createStatement();
        ResultSet rs = statement.executeQuery(query1);
        
        Employee employee;
        while(rs.next()){
           employee = new Employee(rs.getInt("EmpNo"), rs.getString("EmpName"), rs.getInt("ContactNo"), rs.getString("Position"), 
                                        rs.getString("Department"), rs.getInt("PayRate"), rs.getString("PR_Per"), rs.getString("TaxExempt"),
                                          rs.getString("Classification"), rs.getString("MaritalStatus"), rs.getInt("Bonus"), rs.getString("TOE"), rs.getString("LDW"), rs.getString("Eligibility"));
           employeeList.add(employee);
        }
     
        
        
        } catch (Exception e) {
            System.out.print(e);
        }
        return employeeList;
    }
    
    public void display_employee(){
        ArrayList<Employee> list = employeeList();
        DefaultTableModel model = (DefaultTableModel)EmployeeTable.getModel();
        Object [] row = new Object [14];
        for(int i = 0; i<list.size(); i++){
            row[0] = list.get(i).getEmpNo();
            row[1] = list.get(i).getEmpName();
            row[2] = list.get(i).getContactNo();
            row[3] = list.get(i).getPosition();
            row[4] = list.get(i).getDepartment();
            row[5] = list.get(i).getPayRate();
            row[6] = list.get(i).getPR_Per();
            row[7] = list.get(i).getTaxExempt();
            row[8] = list.get(i).getClassification();
            row[9] = list.get(i).getMaritalStatus();
            row[10] = list.get(i).getBonus();
            row[11] = list.get(i).getTOE();
            row[12] = list.get(i).getLDW();
            row[13] = list.get(i).getEligibility();
            model.addRow(row);
            
        }
            
        
    }

                           
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void refreshTable() {
    // Clear the existing data from the table model
    DefaultTableModel model = (DefaultTableModel) EmployeeTable.getModel();
    model.setRowCount(0);
    display_employee();
    }
    
    private void deleteEmployee(int empNO) {
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/hrdatavault", "root", "@forgotpassword123");
        String deleteEmployeeQuery = "DELETE FROM Employee WHERE EmpNo=?";
            try (PreparedStatement deleteEmployeeStatement = connection.prepareStatement(deleteEmployeeQuery)) {
                deleteEmployeeStatement.setInt(1, empNO);  
                int rowsDeleted = deleteEmployeeStatement.executeUpdate();
                if (rowsDeleted > 0) {
                    
                    JOptionPane.showMessageDialog(null, "Employee deleted successfully");
                    refreshTable();
                } else {
                
                    JOptionPane.showMessageDialog(null, "Error: Failed to delete employee");
                }
            }
        
        String deleteDependentsQuery = "DELETE FROM Dependents WHERE EmpNo=?";
            try (PreparedStatement deleteDependentsStatement = connection.prepareStatement(deleteDependentsQuery)) {
                deleteDependentsStatement.setInt(1, empNO);
                deleteDependentsStatement.executeUpdate();
            }

        // Execute the update query to delete the employee

        connection.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
    
}
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        EmployeeTable = new javax.swing.JTable();
        Delete = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(241, 239, 239));
        setBorder(null);
        setPreferredSize(new java.awt.Dimension(856, 652));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EmployeeTable.setAutoCreateRowSorter(true);
        EmployeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EmpNo", "EmpName", "Contact No", "Position", "Department", "PayRate", "PR_Per", "TaxExempt", "Classification", "MaritalStatus", "Bonus", "TOE", "LDW", "Eligibility"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        EmployeeTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        EmployeeTable.setAutoscrolls(false);
        EmployeeTable.setGridColor(new java.awt.Color(204, 204, 204));
        EmployeeTable.setIntercellSpacing(new java.awt.Dimension(0, 3));
        EmployeeTable.setSelectionBackground(new java.awt.Color(255, 51, 153));
        EmployeeTable.setShowHorizontalLines(true);
        jScrollPane2.setViewportView(EmployeeTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 560, 480));

        Delete.setBackground(new java.awt.Color(51, 0, 51));
        Delete.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        Delete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.setText("Delete Employee");
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMouseClicked(evt);
            }
        });
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 190, 40));

        jButton2.setBackground(new java.awt.Color(255, 0, 255));
        jButton2.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Add Employee");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 190, 40));

        jButton3.setBackground(new java.awt.Color(153, 0, 153));
        jButton3.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Update Employee");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 190, 40));

        jPanel1.setBackground(new java.awt.Color(241, 239, 239));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AddEmp pi = new AddEmp();
        pi.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

    }//GEN-LAST:event_jButton2MouseClicked

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteActionPerformed

    private void DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseClicked
     int selectedRow = EmployeeTable.getSelectedRow();

    if (selectedRow >= 0) {
        Integer empNO = (Integer) EmployeeTable.getValueAt(selectedRow, 0);
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this employee?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            deleteEmployee(empNO);
            refreshTable();
        }
    } else {
        JOptionPane.showMessageDialog(null, "Please select a row in the Table");
    }
    }//GEN-LAST:event_DeleteMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
  int selectedRow = EmployeeTable.getSelectedRow();
    
    if (selectedRow >= 0) {
        String selectedString = (String) EmployeeTable.getValueAt(selectedRow, 1);
        Integer empNO = (Integer) EmployeeTable.getValueAt(selectedRow, 0);
        UpdateEmp add = new UpdateEmp();
        add.setPassedInteger(empNO);
        add.setVisible(true);
    }
    else{
        JOptionPane.showMessageDialog(null,"Please select a row in the Table");
    }
    }//GEN-LAST:event_jButton3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JTable EmployeeTable;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
